In [2]:
import numpy

In [3]:
x=numpy.array([11,22,33,44])

In [4]:
x

array([11, 22, 33, 44])

In [5]:
print(x)

[11 22 33 44]


In [6]:
import numpy as np

In [7]:
y=np.array([11,22,33,44])

In [8]:
print(y)

[11 22 33 44]


In [9]:
print(x+y)

[22 44 66 88]


In [10]:
print(np.__version__)

1.20.1
